### ISSUE TITLE
feature: show GH stars

### ISSUE THREAD

**Issue by CFenner** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#1]
Nice work. It would be nice to see and order by GH stars.

**Comment by KristjanESPERANTO** [comment]
Yes, that would be nice! :slightly_smiling_face:  I had already made an attempt but abandoned it. I'll try to look at it again in the next few days. A PR would of course also be welcome.

**Comment by KristjanESPERANTO** [comment]
I have implemented this :rocket: 

For non-GitHub repositories there is still some fine-tuning to do, I have created an extra issue for this: #5.
