### ISSUE TITLE
Issues are not enabled in the GitHub repository.

### ISSUE THREAD

**Issue by bugsounet** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#10]
in `result.md`, I can see this:
`Issues are not enabled in the GitHub repository. So users cannot report bugs. Please enable issues in your repo.`

In my case all issues is reported in my own forum
 * maybe you can bypass it with `noGitHubIssues: true,` in package.json (new value)
 * maybe use
 ```
 "bugs": {
  "urls" :"https://....."
 },
```
 
maybe this rule: 
 If "Issues are not enabled in the GitHub repository." and "noGitHubIssues" and bugs.urls --> bypassed
 else display your actual message

**Comment by KristjanESPERANTO** [comment]
Okay, we can do something about that. I'll try to adapt it soon.

The field is originally called "url" and not "urls", right? Have you set this in your modules?

**Comment by bugsounet** [comment]
Ready for testing with https://github.com/bugsounet/EXT-Detector/pull/92

**Comment by KristjanESPERANTO** [comment]
I fixed it :smiley:
