### ISSUE TITLE
Add darkmode

### ISSUE THREAD

**Issue by KristjanESPERANTO** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#14]
Darkmode would be nice. Maybe something similar to [this](This could be an https://www.zigbee2mqtt.io/supported-devices/).

**Comment by yashwanth0010** [comment]
main/docs/index.html is this where the dark mode be implemented? If yes I would do it.

**Comment by KristjanESPERANTO** [comment]
Yes, exactly this file. It would be great if you could do that! 😃

**Comment by KristjanESPERANTO** [comment]
Thanks @yashwanth0010 we have now a dark mode switch (#15)! 🚀
