### ISSUE TITLE
what's `Warning` tag ?

### ISSUE THREAD

**Issue by bugsounet** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#16]
i see :
![image](https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/assets/30669209/06a683aa-73d9-477a-81be-10906891d6d1)

what 's this tag ?

**Comment by KristjanESPERANTO** [comment]
That's a keyword from your package.json. In your module EXT-Internet you added it 3 years ago: https://github.com/bugsounet/EXT-Internet/blame/master/package.json#L18

**Comment by bugsounet** [comment]
powa ... i'm stupid sorry :/

I look any modules that i have not patched :(

**Comment by KristjanESPERANTO** [comment]
No problem :+1: :smiley:
