### ISSUE TITLE
ownList

### ISSUE THREAD

**Issue by bugsounet** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#17]
I make my ownlist (very long !)

are there any possibilities to have result.md only with it ?

Actually, it's include all modules and ownlist in result.md

**Comment by KristjanESPERANTO** [comment]
Oh, I'll check that.

**Comment by bugsounet** [comment]
This is my ownList:

[ownModuleList.json](https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/files/14396869/ownModuleList.json)

**Comment by KristjanESPERANTO** [comment]
I made a mistake in the ownList script call. I just fixed it :smiley:

**Comment by bugsounet** [comment]
works fine after #18 ;)

**Comment by bugsounet** [comment]
now... it will be very interesting :)

but... my `ownModuleList.json` will be erased on each update :/
maybe you can try to code something like `npm run ownList <file.json>`

**Comment by bugsounet** [comment]
humm... the problem with me ... when i have an idea... I do it now and I code it :)))
So let's open my dev tools :)

**Comment by KristjanESPERANTO** [comment]
Thanks for the fix! :rocket: 

> but... my ownModuleList.json will be erased on each update :/
> maybe you can try to code something like npm run ownList <file.json>

I'm on it now. Update will come in a couple of minutes.

**Comment by KristjanESPERANTO** [comment]
I just added the file to .gitignore. Is that enough?

**Comment by bugsounet** [comment]
~or rename it as .sample~ just see that you do it

So ;)

I write

```
bugsounet@Kubuntu:~/MagicMirror-3rd-Party-Modules$ npm run testage perso.json

> magicmirror-3rd-party-modules@0.1.0 testage
> node create_own_module_list.js perso.json

Found: perso.json
write: {
  lastUpdate: '2024-02-25T22:04:47.509Z',
  modules: [
    {
   <...>
```

**Comment by KristjanESPERANTO** [comment]
The idea is that you continue to use `ownModuleList.json`. Than you only have to run `npm run ownList` without any parameter.

**Comment by bugsounet** [comment]
I understood :=) 
but I prefert to purpose another solution in case you are interested ;)

**Comment by KristjanESPERANTO** [comment]
You prefer to be able to use a file name as a parameter to use different custom lists?

**Comment by bugsounet** [comment]
no,no it's ok for me ;)
