### ISSUE TITLE
How to add tags?

### ISSUE THREAD

**Issue by dathbe** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#22]
Is there a way for users to add tags, or is that only available for devs/automatic?  For example, the MMM-MyScoreboard module has the tag `sports`, but not `sport`, which means it does not come up when you filter using the `sport` button in the menu bar.

**Comment by KristjanESPERANTO** [comment]
Good advice! :smiley: What would you recommend as the main tag `sport` or `sports`?

I could merge both or we create PRs to harmonize that.

Now `sports` is used one time and `sport` is used four times.

**Comment by dathbe** [comment]
"Sports" is what I use.  But I think most of the rest of the world uses "sport".  Is there a way to grab "sport*" and label it one or the other?  I don't care what it's labeled, but American devs will tend toward listing "sports" and others "sport".  You'll have a hard time getting everyone to be consistent.

**Comment by KristjanESPERANTO** [comment]
Okay, I have just implemented that the keyword "Sport" is replaced by "Sports" :runner: :slightly_smiling_face:
