### ISSUE TITLE
Changing primary branch name to 'main' will prevent "git pull" from working

### ISSUE THREAD

**Issue by dathbe** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#24]
The dev recommendations suggest changing any primary branches named `master` (a lot of them) to `main`.  As far as I can tell, this is a purely cosmetic/semantic change, but when it is done on any module it prevents git pull from working, giving the following error:

```
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
```

I would suggest removing this recommendation (or providing instructions for working around this issue)

**Comment by KristjanESPERANTO** [comment]
You're right, this is a hint that can cause problems. I switched all my modules before they were used by many people, so I didn't need a clean migration strategy. 

Without precise instructions on how it can be done smoothly, this is not ideal... I'll try to tackle this soon when I can clear my head. Suggestions are always welcome :-)

**Comment by dathbe** [comment]
I get that the word `master` has some historical connotations, but given that there's no functional difference...and most people won't even see the branch name when they `git clone`, my recommendation would be just leaving it as is, and encouraging new devs to use `main.`  I think `main` is the default for new repositories.

**Comment by KristjanESPERANTO** [comment]
Hm... okay, without instructions on how to change the branch of your module without problems for the users, it makes little sense to list it. I don't see a solution for this right now, so I have just deactivated this check.
