### ISSUE TITLE
feature: filtering for categories/all tags

### ISSUE THREAD

**Issue by klaernie** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#3]
I think it would be nice to take the categories for modules present on the official list and make them tags as well, so one can filter for them. But maybe that would require a different tag selector (somehow the one from [Zigbee2MQTT Supported Devices](https://www.zigbee2mqtt.io/supported-devices/) comes into my mind).

Also I think having the tags listed with each module should be clickable, and return the other modules with the same tag.

**Comment by KristjanESPERANTO** [comment]
> take the categories for modules present on the official list

Adopting the old categories was also my first plan. But somehow the idea came up to drop them and insert certain tags at the top as buttons instead. I thought that would be a good replacement.

> somehow the one from [Zigbee2MQTT Supported Devices](https://www.zigbee2mqtt.io/supported-devices/) comes into my mind

A lot of things have been nicely implemented on that page, and we could certainly adapt a few approaches for our page.

> Also I think having the tags listed with each module should be clickable, and return the other modules with the same tag.

That would be a nice new feature! I'm focusing on other things at the moment, but we can definitely tackle that. I set the tag specifically for this to "good first issue".

**Comment by KristjanESPERANTO** [comment]
With https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/commit/c1c00eedc5dcd99c10087d60f7158aad11fd305a the tags in the cards are now clickable :smiley:
