### ISSUE TITLE
MMM-Multimonth License issues? 

### ISSUE THREAD

**Issue by BKeyport** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#30]
Per your issues page, My license info is all messed up - can you look at my package.json and figure out why? It seems saying my license is NOASSERTION - should be "MIT-Modern-Variant" 

Thanks.

**Comment by BKeyport** [comment]
Nevermind, I just noticed it's looking for the LICENSE file, not LICENSE.md

**Comment by KristjanESPERANTO** [comment]
My script uses the GitHub API and not the LICENSE file directly. NOASSERTION means that GitHub does not recognize the license from the license file text. Under which license do you want to publish your module?

**Comment by BKeyport** [comment]
I actually was going to reopen this later today. I like
the MIT-Modern-Variant

**Comment by BKeyport** [comment]
Status: Still broken. 

LICENSE file: 

```
Copyright © 2020-2025 Brendan Keyport. All rights reserved.

Permission is hereby granted, without written agreement and without license or royalty fees, to use, copy, modify, and distribute this software and its documentation for any purpose, provided that the above copyright notice and the following two paragraphs appear in all copies of this software.

IN NO EVENT SHALL BRENDAN KEYPORT et al.  BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF BRENDAN KEYPORT et al  HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

BRENDAN KEYPORT et al. SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND BRENDAN KEYPORT et al.  HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

```

https://spdx.org/licenses/MIT-Modern-Variant.html it the template I used.

**Comment by KristjanESPERANTO** [comment]
Somehow I feel that the modern MIT version is worse than the classic one...

Please try [my PR](https://github.com/BKeyport/MMM-Multimonth/pull/22). It could be the year, the double spaces and/or the ‘et al.’.

**Comment by KristjanESPERANTO** [comment]
Saddly I doubt that this solved the problem. The title still only says `Licence` and not `MIT licence` as in the MagicMirror repo.

I'm afraid this is a GitHub problem. GitHub doesn't seem to recognise the MIT-Modern-Variant yet. 

![bildo](https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/assets/35647502/1c8e4599-9e9b-4b9c-818c-1be22e4f9682)

![bildo](https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/assets/35647502/78fb9d11-a169-4497-b154-dc70fe136072)

**Comment by BKeyport** [comment]
Alright, it's switched over to the MIT regular license (Grumble)

**Comment by KristjanESPERANTO** [comment]
Okay, now MIT is also displayed for your module 🙂. Too bad that GitHub can't handle the "modern" version yet.
