### ISSUE TITLE
mmm-pir module

### ISSUE THREAD

**Issue by tommyklalau** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#34]
Is it possible to set the relay toggling not only when switching on or off, but during both state changes. So a toggle when switching off and a toggle when switching on.
The background is that I want to use the relay to operate my standby button on the monitor.
The relay currently switches off after a set time and switches on again when there is movement. This switches the supply voltage completely. It would be better to leave the power supply permanently connected and only switch the stanby button. But for this you need a change in the state of the relay with every process.
I couldn't get it to work in the settings. where can you change the behavior of the relay? mode 6 and mod 7 at the same time so to speak.

https://github.com/bugsounet/MMM-Pir

**Comment by KristjanESPERANTO** [comment]
Hi @tommyklalau, sorry, this is not the place to handle specific issues of a module. I don't know why the issues are disabled in that repository. Please get in touch with the developer @bugsounet 🙂
