### ISSUE TITLE
eslint / eslint-plugin-import problem ?

### ISSUE THREAD

**Issue by bugsounet** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#35]
Hi Kristjan,

can you check [this](https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/blob/main/result.md#mmm-googleassistant-by-bugsounet)

my linter report no problem: see [there](https://github.com/bugsounet/MMM-GoogleAssistant/commit/ad5a9fd09fbe0f814c0d74b3b02a820534971bfd)

in eslint config, i have `"import/no-unresolved": "error",` and no error is reported
my test result: [there](https://github.com/bugsounet/MMM-GoogleAssistant/actions/runs/11869759759/job/33080421727)

**Comment by KristjanESPERANTO** [comment]
Thanks for the details! I'll try to have a look at it soon :slightly_smiling_face:

**Comment by bugsounet** [comment]
if it's on my side, tell me :)

**Comment by KristjanESPERANTO** [comment]
I decided to disable this rule. Done by commit f6e7c5f5b22da212ef91a92a12903d5add532980 :slightly_smiling_face:
