### ISSUE TITLE
ignore *.min.js file

### ISSUE THREAD

**Issue by bugsounet** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#36]
maybe it's better to ignore *.min.js file from modules checker linter ?

What do you think about this ?

**Comment by bugsounet** [comment]
Sample [there](https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/blob/main/result.md#ext-smarthome-by-bugsounet)

**Comment by KristjanESPERANTO** [comment]
Makes sense! :slightly_smiling_face:

Fixed with c82de3cdc4ca239749ccf24487ba2a61ea3b05fb.
