### ISSUE TITLE
Improve CSS

### ISSUE THREAD

**Issue by KristjanESPERANTO** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#6]
Reported by @Fabrizz :

> About the page, in mobile the card are smaller than the screen width, some icons are not shown.

> In desktop I would have a max width for the card container, as if the screen is too big it would just expand.

**Comment by bugsounet** [comment]
Hi Kristjan, I see that `sort` menu is not displayed on an mobile page
I don't know if it's related to CSS or main core.

In all case good job !
it is now embed into the `MMM-GoogleAssistant` website :)

**Comment by KristjanESPERANTO** [comment]
Thanks for the feedback! I've just improved a few details for the mobile version :smiley: 

With this I close the issue for now. If you notice anything else about the styling, please let me know here or in a new issue.

> it is now embed into the MMM-GoogleAssistant website :)

That's really cool! Thank you :slightly_smiling_face:

**Comment by Fabrizz** [comment]
Im changing a bit the cards so the images are not that big, will create the pr
<img width="809" alt="image" src="https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/assets/65259076/8d4699c1-8b7a-4f53-b13a-f08b7557bc9b">

**Comment by KristjanESPERANTO** [comment]
I like it! Thanks in advance! :smiley:

Would be nice if you would also add a before-screenshot in the PR.

**Comment by KristjanESPERANTO** [comment]
Since @Fabrizz made some changes by PR #7 I close this issue :slightly_smiling_face:
